##############################################################################
#  Copyright Christopher Kormanyos 2021 - 2022.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: e_float
on:
  push:
jobs:
  apple-gcc-clang-native-efx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [ E_FLOAT_TEST_REAL_IMAG_TESTS, E_FLOAT_TEST_PI_ALGOS_TESTS ]
        standard: [ c++11, c++14, c++17, c++2a ]
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: apple-gcc-clang-native-efx
        run: |
          make MP=efx TYP_TOOLSET=${{ matrix.compiler }} TYP_STD=${{ matrix.standard }} TYP_TEST=${{ matrix.suite }} rebuild
          ls -la ./unix-efx/e_float.exe
          ./unix-efx/e_float.exe
        working-directory: ./libs/e_float/build/
