name: e_float_archs
on: [push]
jobs:
  release-efx-archs:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - name: IBM Z and LinuxONE
            architecture: "s390x"
          - name: POWER8
            architecture: "ppc64le"
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@master
        with:
          architecture: ${{ matrix.arch.architecture }}
          distribution: ubuntu18.04
          run: |
            ls -la
            g++ -v
