name: e_float_archs
on: [push]
jobs:
  release-efx-archs:
    strategy:
      fail-fast: false
      matrix:
        architecture: [ s390x, ppc64le ]
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@master
        with:
          architecture: ${{ matrix.architecture }}
          distribution: ubuntu18.04
          run: |
            sudo apt install gcc
            ls -la
            g++ -v
