##############################################################################
#  Copyright Christopher Kormanyos 2021.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp
on: [push,pull_request]
jobs:
  msvc-release-efx:
    runs-on: windows-latest
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: msvc-release-efx
        shell: pwsh
        env:
          PATH: '${env:PATH};C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64'
        run: |
          MSBuild -m e_float.sln -p:Configuration=release-efx -p:Platform=x64 /t:Rebuild
          dir ./x64-release-efx/e_float.exe
          ./x64-release-efx/e_float.exe
        working-directory: ./libs/e_float/build/
