##############################################################################
#  Copyright Christopher Kormanyos 2021.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: e_float
on: [push]
jobs:
  gcc-native-efx-platforms:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        suite: [ E_FLOAT_TEST_REAL_IMAG_TESTS, E_FLOAT_TEST_PI_ALGOS_TESTS ]
        standard: [ c++11, c++14, c++17 ]
        compiler: [ g++ ]
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: gcc-native-efx-platforms
      - uses: uraimo/run-on-arch-action@v2.0.5
        id: runcmd
        with:
          arch: ppc64le
          distro: ubuntu20.04
        run: |
          make MP=efx TYP_TOOLSET=${{ matrix.compiler }} TYP_STD=${{ matrix.standard }} TYP_TEST=${{ matrix.suite }} rebuild
          ls -la ./unix-efx/e_float.exe
          ./unix-efx/e_float.exe
        working-directory: ./libs/e_float/build/
