##############################################################################
#  Copyright Christopher Kormanyos 2021.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: libe_float
on: [push]
jobs:
  gcc-native-libe_float:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        mptype: [ efx, gmp, mpfr ]
    if: "!contains(github.event.commits[0].message, '[CI SKIP]')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install packages
        run: sudo apt install libgmp-dev libmpfr-dev
      - name: gcc-native-libe_float
        run: |
          make MP=${{ matrix.mptype }} TYP_TOOLSET=g++ TYP_STD=c++11 TYP_TEST=E_FLOAT_TEST_REAL_IMAG_TESTS rebuild
          echo run ./unix-${{ matrix.mptype }}/e_float.exe
          ./unix-${{ matrix.mptype }}/e_float.exe
          echo create archive ./unix-${{ matrix.mptype }}/libe_float.a
          cd ./unix-${{ matrix.mptype }}/obj
          ar cr ../libe_float.a e_float_${{ matrix.mptype }}.o e_float.o e_float_base.o constants.o elementary_complex.o elementary_hyper_g.o elementary_math.o elementary_trans.o elementary_trig.o
          cd ../../
          ls -la ./unix-${{ matrix.mptype }}/e_float.exe ./unix-${{ matrix.mptype }}/libe_float.a
        working-directory: ./libs/e_float/build
